### ISSUE TITLE
no longer autostarts after reboot

### ISSUE THREAD

**Issue by habra-cadabra** [hankhank10/music-screen-api#36]
hello!

music-screen-api doesn't launch at startup starting at commit #33. I reverted back to #32 and everything starts as normal. 

running "DISPLAY=:0 /usr/bin/python3 /home/pi/music-screen-api/go_sonos_highres.py" on #33 or #34 starts music-screen-api normally.

**Comment by jjlawren** [comment]
Any logs or tracebacks?

**Comment by habra-cadabra** [comment]
yep, sorry! got sidetracked. 

2020-08-13 22:09:56,112   ERROR - Task exception was never retrieved
future: <Task finished coro=<main() done, defined at /home/pi/music-screen-api/go_sonos_highres.py:171> exception=CalledProcessError(128, ['git', 'describe'])>
Traceback (most recent call last):
  File "/home/pi/music-screen-api/go_sonos_highres.py", line 174, in main
    log_git_hash()
  File "/home/pi/music-screen-api/go_sonos_highres.py", line 129, in log_git_hash
    git_hash = subprocess.check_output(["git", "describe"], text=True).strip()
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.

**Comment by jjlawren** [comment]
Ok thanks, the reason is clear. I'll try to take a look at it tomorrow.
